services:
  backend:
    image: my-backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: backend
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
