name: Build and Push to ACR

on: workflow_call

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: <your-acr-name>.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push Docker images
        run: |
          docker build -t <your-acr-name>.azurecr.io/yourapp-backend:latest ./backend
          docker build -t <your-acr-name>.azurecr.io/yourapp-frontend:latest ./frontend
          docker push <your-acr-name>.azurecr.io/yourapp-backend:latest
          docker push <your-acr-name>.azurecr.io/yourapp-frontend:latest
