name: Rust-Angular CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build Rust Backend
        run: cargo build --release

      - name: Run Rust Unit Tests
        run: cargo test

  build-and-test-angular:
    runs-on: ubuntu-latest
    needs: build-and-test-rust
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust based on your version

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Frontend
        run: ng build

      - name: Run Angular Unit Tests
        run: ng test --watch=false --browsers=ChromeHeadless

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test-angular
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          password: ${{ secrets.PI_PASSWORD }}
          script: |
            cd /path/to/your/application
            docker-compose up -d

