name: Test Backend

on: workflow_call

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            target
            ~/.cargo/git
            ~/.cargo/registry
            ~/Cargo.lock
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock')}}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build and Test
        env:
          SQLX_OFFLINE: "true"
        run: |
          cd backend
          cargo build --release
          cargo test
